---
title: "Gap Maps"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r map gaps, message=FALSE, warning=FALSE}

if (!require(pacman)) install.packages("pacman")
library(pacman)
p_load(
  tidyverse, here, glue,
  raster,
  sdmpredictors, dismo, 
  deldir, 
  mapview,
  tmap,
  ggplot2,
  rgdal,
  gstat,
  usdm,
  knitr,
  tmap,
  rnaturalearth)

tmap_mode("view")

pal <- colorRampPalette(c("royalblue2", "white", "red"))

tm_shape(gap)+
  tm_raster(palette = pal(10), colorNA = NULL, alpha = 0.8, auto.palette.mapping = FALSE, breaks = c(0, 25, 50, 75, 100, 125, 150), title = "Effective Distance to Nearest Monitoring (km)")+
  tm_layout(main.title = "Effective Distance to Nearest Monitoring (km)", fontfamily = "serif", fontface = "bold", main.title.size = 1)+
  tm_shape(poly_coast)+
  tm_polygons()+
  tm_shape(Canada)+
  tm_polygons()+
  tm_grid(projection = "longlat", lwd = 0.1, n.x = 3, n.y = 6, labels.size = 0.6)+
  tmap_options(max.raster = c(plot = 45955000, view = 45955000))

tm_shape(carbcompletegap)+
  tm_raster(palette = pal(10), colorNA = NULL, alpha = 0.8, breaks = c(0, 25, 50, 75, 100, 125, 150), auto.palette.mapping = FALSE, title = "Effective Distance to Nearest Monitoring (km)")+
  tm_layout(main.title = "Effective Distance to Nearest Aragonite Monitoring (km)", fontfamily = "serif", fontface = "bold", main.title.size = 1)+
  tm_shape(poly_coast)+
  tm_polygons()+
  tm_shape(Canada)+
  tm_polygons()+
  tm_grid(projection = "longlat", lwd = 0.1, n.x = 3, n.y = 6,labels.size = 0.6)+
  tmap_options(max.raster = c(plot = 45955000, view = 45955000))

tm_shape(highfreqgap)+
  tm_raster(palette = pal(10), colorNA = NULL, alpha = 0.8, breaks = c(0, 25, 50, 75, 100, 125, 150), auto.palette.mapping = FALSE, title = "Effective Distance to Nearest Monitoring (km)")+
  tm_layout(main.title = "Effective Distance to Nearest Daily Monitoring (km)", fontfamily = "serif", fontface = "bold", main.title.size = 1)+
  tm_shape(poly_coast)+
  tm_polygons()+
  tm_shape(Canada)+
  tm_polygons()+
  tm_grid(projection = "longlat", lwd = 0.1, n.x = 3, n.y = 6, labels.size = 0.6)+
  tmap_options(max.raster = c(plot = 45955000, view = 45955000))

```
